spring.application.name=poc-spring-batch
server.port=8080

spring.datasource.url=jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

batch.input.directory=C:/batch-input

app.jwt.secret=MySecretKeyForJwtTokenMustBe256BitsLongAtLeast12345
app.jwt.expiration-minutes=5

logging.level.com.poc=DEBUG
logging.level.org.springframework.batch=INFO
logging.level.org.springframework.security=WARN